### ISSUE TITLE
search blackout

### ISSUE THREAD

**Issue by coldtoon** [Inrixia/inrixia.github.io#2]
![image](https://user-images.githubusercontent.com/12128712/36233601-d713333c-11b4-11e8-9d2e-85423ee495ea.png)

i hope this uploaded right

**Comment by Inrixia** [comment]
Thanks, Ill work on fixing it in a bit.

**Comment by coldtoon** [comment]
ehh its a new site format

**Comment by Inrixia** [comment]
Fixed, updated both the Script and Stylish versions.
